# Generated by Django 4.2.20 on 2025-05-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_email', models.CharField(max_length=30)),
                ('a_pwd', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
                ('p_price', models.CharField(max_length=30)),
                ('p_rating', models.IntegerField()),
                ('p_det', models.CharField(max_length=500)),
                ('p_cat', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30)),
                ('u_phone', models.CharField(max_length=15)),
                ('u_add', models.CharField(max_length=15)),
                ('u_gender', models.CharField(max_length=15)),
                ('u_email', models.EmailField(max_length=254)),
                ('u_pwd', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateField()),
                ('p_status', models.CharField(max_length=30)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
