# Generated by Django 4.2.20 on 2025-05-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_date', models.DateField()),
                ('d_name', models.CharField(max_length=30)),
                ('d_add', models.CharField(max_length=50)),
                ('d_location', models.CharField(max_length=500)),
                ('total_amout', models.CharField(max_length=30)),
                ('p_status', models.CharField(max_length=30)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='P_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
                ('p_image', models.ImageField(upload_to='product_images/')),
                ('p_quantity', models.IntegerField()),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'P_order',
            },
        ),
    ]
