# Generated by Django 4.2.20 on 2025-05-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_p_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_order',
            name='p_subtital',
            field=models.CharField(default='defultvalue', max_length=30),
            preserve_default=False,
        ),
    ]
