# Generated by Django 4.2.20 on 2025-05-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_p_order_p_subtital'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_order',
            name='p_price',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
