# Generated by Django 4.2.20 on 2025-05-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_p_order_p_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='d_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
